
name: Auto Rebase PRs onto dev

on:
  push:
    branches:
      - main   # mỗi khi dev được update

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get all open PRs targeting dev
        run: |
          prs=$(gh pr list --base dev --state open --json headRefName -q '.[].headRefName')
          echo "PRS=$prs" >> $GITHUB_ENV

      - name: Rebase each PR onto dev
        run: |
          for pr_branch in $PRS; do
            echo "Rebasing $pr_branch onto dev"
            git fetch origin $pr_branch
            git checkout $pr_branch
            git rebase origin/dev || git rebase --abort
            git push --force-with-lease origin $pr_branch || true
          done
